### ISSUE TITLE
Versions listed on the website are out of date

### ISSUE THREAD

**Issue by gwils** [argonaut-io/argonaut.io#7]
At the time of this issue, argonaut.io lists 6.0.4 as the current published version, however 6.1 has been released.

**Comment by seanparsons** [comment]
Good catch!

**Comment by matt-martin** [comment]
Just came here to say this...  It looks like it should've been fixed with this change: https://github.com/argonaut-io/argonaut.io/commit/cb31a3cd85b6ebb5172d14fc940b79ae450e6e35#diff-aeb42283af8ef8e9da40ededd3ae2ab2

But I still see the old versions when visiting http://argonaut.io/:

![screen shot 2016-01-12 at 5 47 28 pm](https://cloud.githubusercontent.com/assets/956900/12282666/9b838296-b954-11e5-9d1c-74c0cb45ee6d.png)

Not familiar enough with github pages to know why that is happening, but I'm guessing that maybe the change just needs to be pushed out somehow?

**Comment by seanparsons** [comment]
Yup, I've just been a little busy the last couple of weeks, when I was planning on doing that.

**Comment by seanparsons** [comment]
This is now sorted and up to date with the 6.2-M1 push.
